# basic parameters
checkpoint_dir: 'checkpoint'
model_path: 'checkpoint/baseline3_explicit/checkpoint/best_dev'
name: 'baseline3_explicit_test'
gpu: 0
per_gpu_batch_size: 8
seed: 0

# evaluation parameters
eval_data: 'explicit_test.json'
write_results: true

# model specific parameters
n_context: 1
text_maxlength: 250
no_sent: false
no_path: false