# basic parameters
checkpoint_dir: 'checkpoint'
model_path: 'checkpoint/baseline2/checkpoint/best_dev'
name: 'baseline2_test'
gpu: 1
per_gpu_batch_size: 8
seed: 0

# evaluation parameters
eval_data: 'test.json'
write_results: true

# model specific parameters
n_context: 1
text_maxlength: 250
no_sent: true
no_path: false