# basic parameters
checkpoint_dir: 'checkpoint'
model_path: 'checkpoint/baseline3_significant/checkpoint/best_dev'
name: 'baseline3_significant_test'
gpu: 2
per_gpu_batch_size: 8
seed: 0

# evaluation parameters
eval_data: 'significant_test.json'
write_results: true

# model specific parameters
n_context: 1
text_maxlength: 250
no_sent: false
no_path: false